language: node_js
node_js:
  - "7"
before_script:
  - npm install -g gulp gulp-cli
script: gulp
branches:
  only:
    - master
after_success:
  - "mkdir site"
  - "cp index.html site/"
  - "cp CNAME site/"
  - "cp -R assets/ site/"
deploy:
  provider: pages
  local_dir: site
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
