language: node_js
node_js:
  - "iojs"
  - "7"
before_script:
  - npm install -g gulp gulp-cli
script: gulp
branches:
  only:
    - develop
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: develop
