language: node_js
node_js:
  - "iojs"
  - "7"
before_script:
  - npm install -g gulp gulp-cli
script: gulp
branches:
  only:
    - develop
deploy:
  provider: script
  script: deploy.sh
  skip_cleanup: false
  on:
    branch: develop
